# Training Model Configuration File

# YOLO Model Parameters / Overrides

data: 'configurations/model_data-seg.yaml' # Data Source

# hardware
device: 'None'              # 'mps' = Apple Metal GPU | None = best fit available
workers: 8                  # keep small on macOS/MPS
amp: True                   # Automatic Mixed Precision (AMP) training, reduces memory usage

# schedule
epochs: 100                  # number of training epochs
patience: 50                 # early stopage if plateaus
imgsz: 832                   # default = 640 
batch: 8                     # T4 + imgsz 832 usually fits 6–10; 8 is safe
nbs: 64                      # default Nominal Batch Size = 64. Decrease to control gradient accummulation factor
seed: 0                      # State for comparisons across hyperparameter changes/model changes

# augmentation (aerial imagery friendly)
copy_paste: 0.10              # Default = 0.0 |helps segmentation; turn down if artifacts appear | Segmentation only. Copies and pastes objects across images to increase object instances.
close_mosaic: 10              # disable mosaic for last 10 epochs to refine details & polish fine edges at the final scale.
mosaic: 0.9                   # Default = 1.0 | Combines four training images into one, simulating different scene compositions and object interactions
scale: 0.7                    # Default - 0.5 | Scales the image by a gain factor, simulating objects at different distances from the camera.
hsv_s: 0.9                    # Default = 0.7 | Increase saturdation of images
hsv_h: 0.028                  # Default = 0.015 | Increase range of Color Hue spectrum durign training
degrees: 180                  # Rotate images up to 180degrees during training

# dataloader
rect: False                   # train with mosaic/crop; keep True only for val/test

# optimizer & LR
# optimizer: 'AdamW'          # optimizer | Resort to default
lr0: 0.003                    # Default = 0.01 | decreased learning rate to minimsize NMS errors 
                                # Rule of Thumb: Smaller effective batch → lower learning rate


# loss balance (segmentation quality ↑, AP75 ↑)
# cls: 0.3                    # Default = 0.5 | Unsuccessful previous training with decereased cls


# organisation
name: 'train_Yolo11s_canopy_832_adamW_'
project: runs/segment       # Output destination
plots: False                # don't draw plots every val
val: True




